# https://render.com/docs/yaml-spec
services:
  - type: web
    region: frankfurt
    name: berlin-datahub-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /api/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: datahub
          property: connectionString
      - key: APP_SECRET
        generateValue: true
databases:
  - name: datahub
    databaseName: datahub
    region: frankfurt
