# This is a basic workflow to help you get started with Actions

name: Build Docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build the docs using typedoc
    steps:
      # To use add these to the repo again
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: install modules
        run: npm ci
      - name: build docs
        run: npm run typedoc
        # https://github.com/marketplace/actions/add-commit?version=v4.4.0
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0 # You can change this to use a specific version
        with:
          add: docs/
          author_name: tsboter
          author_email: roboter@tsb-berlin.de
          message: "Update docs via workflow"
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        # Runs a set of commands using the runners shell
